name: Final WordPress Connection Test

on:
  # این ورک‌فلو فقط به صورت دستی از تب Actions اجرا می‌شود
  workflow_dispatch:

jobs:
  test-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run connection test script
        env:
          # این نام‌ها دقیقاً با نام Secrets شما در گیت‌هاب مطابقت دارند
          WP_URL: ${{ secrets.WP_URL }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_PASSWORD: ${{ secrets.WP_PASSWORD }}
        run: python test_connection.py
